/**
 * End-to-end smoke test for DashSnap.
 * Launches the Electron app, navigates to Google, captures a screenshot, and builds a PPTX.
 * Run: node test/e2e-smoke.cjs
 */
const { app, BrowserWindow, BrowserView } = require('electron');
const path = require('path');
const fs = require('fs');

// Reuse the built config manager
const appDataPath = path.join(require('os').homedir(), 'DashSnap');
const outputDir = path.join(appDataPath, 'output');
const configDir = path.join(appDataPath, 'config');

function ensureDir(d) { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); }
ensureDir(outputDir);
ensureDir(configDir);

app.commandLine.appendSwitch('disable-gpu-cache');

app.whenReady().then(async () => {
  console.log('[SMOKE] Starting DashSnap E2E smoke test...');

  // Create main window
  const win = new BrowserWindow({
    width: 1400,
    height: 900,
    show: true,
    title: 'DashSnap Smoke Test',
    backgroundColor: '#13111C',
  });

  // Create BrowserView
  const view = new BrowserView();
  win.setBrowserView(view);
  view.setBounds({ x: 0, y: 0, width: 1400, height: 900 });
  view.webContents.setUserAgent(
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
  );

  console.log('[SMOKE] Navigating to Google...');
  await view.webContents.loadURL('https://www.google.com');

  // Wait for page to fully render
  await new Promise(r => setTimeout(r, 3000));
  console.log('[SMOKE] Page loaded:', view.webContents.getURL());

  // Take full-page screenshot
  console.log('[SMOKE] Taking screenshot...');
  const image = await view.webContents.capturePage();
  const pngBuffer = image.toPNG();
  const screenshotPath = path.join(outputDir, 'smoke_test_screenshot.png');
  fs.writeFileSync(screenshotPath, pngBuffer);
  console.log('[SMOKE] Screenshot saved:', screenshotPath, `(${pngBuffer.length} bytes)`);

  // Take a region screenshot (simulate SNAP step)
  console.log('[SMOKE] Taking region screenshot (200,100 -> 800x400)...');
  const regionImage = await view.webContents.capturePage({
    x: 200, y: 100, width: 800, height: 400,
  });
  const regionPath = path.join(outputDir, 'smoke_test_region.png');
  fs.writeFileSync(regionPath, regionImage.toPNG());
  console.log('[SMOKE] Region screenshot saved:', regionPath);

  // Build PPTX
  console.log('[SMOKE] Building PowerPoint...');
  try {
    const PptxGenJS = require('pptxgenjs');
    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_WIDE';

    // Slide 1: Full page
    const slide1 = pptx.addSlide();
    slide1.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.6, fill: { color: '13111C' } });
    slide1.addShape(pptx.ShapeType.rect, { x: 0, y: 0.58, w: '100%', h: 0.02, fill: { color: '7C5CFC' } });
    slide1.addText('Google Homepage - Full', { x: 0.4, y: 0.05, w: 8, h: 0.5, fontSize: 16, fontFace: 'Segoe UI', color: 'e2e8f0', bold: true });
    slide1.addImage({
      data: 'image/png;base64,' + pngBuffer.toString('base64'),
      x: 0.3, y: 0.8, w: 12.7, h: 6.2,
      sizing: { type: 'contain', w: 12.7, h: 6.2 },
    });
    const ts = new Date().toLocaleString();
    slide1.addText('Generated by DashSnap — ' + ts, { x: 0.4, y: 7.1, w: 10, h: 0.3, fontSize: 8, fontFace: 'Segoe UI', color: '64748b' });

    // Slide 2: Region
    const slide2 = pptx.addSlide();
    slide2.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: '100%', h: 0.6, fill: { color: '13111C' } });
    slide2.addShape(pptx.ShapeType.rect, { x: 0, y: 0.58, w: '100%', h: 0.02, fill: { color: '10b981' } });
    slide2.addText('Google Homepage - Region Crop', { x: 0.4, y: 0.05, w: 8, h: 0.5, fontSize: 16, fontFace: 'Segoe UI', color: 'e2e8f0', bold: true });
    slide2.addImage({
      data: 'image/png;base64,' + regionImage.toPNG().toString('base64'),
      x: 0.3, y: 0.8, w: 12.7, h: 6.2,
      sizing: { type: 'contain', w: 12.7, h: 6.2 },
    });
    slide2.addText('Generated by DashSnap — ' + ts, { x: 0.4, y: 7.1, w: 10, h: 0.3, fontSize: 8, fontFace: 'Segoe UI', color: '64748b' });

    const now = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const pptxPath = path.join(outputDir, `DashSnap_SmokeTest_${now}.pptx`);
    await pptx.writeFile({ fileName: pptxPath });
    console.log('[SMOKE] PowerPoint saved:', pptxPath);
  } catch (err) {
    console.error('[SMOKE] PPTX build failed:', err);
  }

  // Verify outputs
  console.log('\n[SMOKE] === RESULTS ===');
  const files = fs.readdirSync(outputDir);
  for (const f of files) {
    const stat = fs.statSync(path.join(outputDir, f));
    console.log(`  ${f} — ${(stat.size / 1024).toFixed(1)} KB`);
  }

  console.log('\n[SMOKE] ✓ Smoke test PASSED! All files generated.');
  console.log('[SMOKE] Check:', outputDir);

  // Keep window open for 3 seconds to see it
  await new Promise(r => setTimeout(r, 3000));
  app.quit();
});
