import PptxGenJS from 'pptxgenjs';
import path from 'path';
import fs from 'fs';
import { nativeImage } from 'electron';
import { ConfigManager } from './config-manager';
import type { PptxLayout } from '../shared/types';

const DEFAULT_LAYOUT: PptxLayout = {
  imageX: 0.3,
  imageY: 0.8,
  imageW: 12.7,
  imageH: 6.2,
  showHeader: true,
  showFooter: true,
  fitMode: 'contain',
};

export class PptxBuilder {
  private config: ConfigManager;

  constructor(config: ConfigManager) {
    this.config = config;
  }

  async build(
    flowId: string,
    screenshots: Array<{ name: string; path: string }>,
  ): Promise<string> {
    const flowConfig = this.config.loadFlows();
    const flow = flowConfig.flows.find((f: { id: string }) => f.id === flowId);
    const settings = this.config.loadSettings();
    const layout: PptxLayout = { ...DEFAULT_LAYOUT, ...settings.pptxLayout };

    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_WIDE'; // 13.33 x 7.5 inches (16:9)

    // Theme colors (charcoal-indigo)
    const headerBg = '13111C';
    const headerText = 'EEEDF5';
    const accentColor = '7C5CFC';
    const footerText = '716D87';

    for (const screenshot of screenshots) {
      const slide = pptx.addSlide();

      // Header bar (optional)
      if (layout.showHeader) {
        slide.addShape(pptx.ShapeType.rect, {
          x: 0, y: 0, w: '100%', h: 0.6,
          fill: { color: headerBg },
        });
        slide.addShape(pptx.ShapeType.rect, {
          x: 0, y: 0.58, w: '100%', h: 0.02,
          fill: { color: accentColor },
        });
        slide.addText(screenshot.name, {
          x: 0.4, y: 0.05, w: 8, h: 0.5,
          fontSize: 16, fontFace: 'Segoe UI', color: headerText, bold: true,
        });
      }

      // Screenshot image
      if (fs.existsSync(screenshot.path)) {
        const imageBuffer = fs.readFileSync(screenshot.path);
        const imageData = imageBuffer.toString('base64');
        const img = nativeImage.createFromBuffer(imageBuffer);
        const imgSize = img.getSize();

        if (layout.fitMode === 'stretch') {
          // Stretch to fill the defined area exactly
          slide.addImage({
            data: `image/png;base64,${imageData}`,
            x: layout.imageX,
            y: layout.imageY,
            w: layout.imageW,
            h: layout.imageH,
          });
        } else if (layout.fitMode === 'fill') {
          // Fill the area (may crop)
          slide.addImage({
            data: `image/png;base64,${imageData}`,
            x: layout.imageX,
            y: layout.imageY,
            w: layout.imageW,
            h: layout.imageH,
            sizing: { type: 'cover', w: layout.imageW, h: layout.imageH },
          });
        } else {
          // 'contain' — preserve aspect ratio, centered in the defined area
          let imgW = imgSize.width / 96;
          let imgH = imgSize.height / 96;

          if (imgW > layout.imageW || imgH > layout.imageH) {
            const scale = Math.min(layout.imageW / imgW, layout.imageH / imgH);
            imgW *= scale;
            imgH *= scale;
          }

          const x = layout.imageX + (layout.imageW - imgW) / 2;
          const y = layout.imageY + (layout.imageH - imgH) / 2;

          slide.addImage({
            data: `image/png;base64,${imageData}`,
            x, y, w: imgW, h: imgH,
          });
        }
      }

      // Footer (optional)
      if (layout.showFooter) {
        const timestamp = new Date().toLocaleDateString('en-US', {
          year: 'numeric', month: 'short', day: 'numeric',
          hour: '2-digit', minute: '2-digit',
        });
        slide.addText(`Generated by DashSnap — ${timestamp}`, {
          x: 0.4, y: 7.1, w: 10, h: 0.3,
          fontSize: 8, fontFace: 'Segoe UI', color: footerText,
        });
      }
    }

    // Generate output path
    const outputDir = settings.outputPath ||
      path.join(this.config.getBasePath(), '..', 'output');
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

    const now = new Date();
    const ts = now.toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const filename = `DashSnap_${ts}.pptx`;
    const outputPath = path.join(outputDir, filename);

    await pptx.writeFile({ fileName: outputPath });
    return outputPath;
  }
}
