import PptxGenJS from 'pptxgenjs';
import path from 'path';
import fs from 'fs';
import { ConfigManager } from './config-manager';

export class PptxBuilder {
  private config: ConfigManager;

  constructor(config: ConfigManager) {
    this.config = config;
  }

  async build(
    flowId: string,
    screenshots: Array<{ name: string; path: string }>,
  ): Promise<string> {
    const flowConfig = this.config.loadFlows();
    const flow = flowConfig.flows.find((f: { id: string }) => f.id === flowId);
    const settings = this.config.loadSettings();

    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_WIDE'; // 16:9

    // Theme colors (charcoal-indigo)
    const headerBg = '13111C';
    const headerText = 'EEEDF5';
    const accentColor = '7C5CFC';
    const footerText = '716D87';

    for (const screenshot of screenshots) {
      const slide = pptx.addSlide();

      // Dark header bar
      slide.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: 0,
        w: '100%',
        h: 0.6,
        fill: { color: headerBg },
      });

      // Accent line under header
      slide.addShape(pptx.ShapeType.rect, {
        x: 0,
        y: 0.58,
        w: '100%',
        h: 0.02,
        fill: { color: accentColor },
      });

      // Title in header
      slide.addText(screenshot.name, {
        x: 0.4,
        y: 0.05,
        w: 8,
        h: 0.5,
        fontSize: 16,
        fontFace: 'Segoe UI',
        color: headerText,
        bold: true,
      });

      // Screenshot image — fill content area
      if (fs.existsSync(screenshot.path)) {
        const imageData = fs.readFileSync(screenshot.path).toString('base64');
        slide.addImage({
          data: `image/png;base64,${imageData}`,
          x: 0.3,
          y: 0.8,
          w: 12.7,
          h: 6.2,
          sizing: { type: 'contain', w: 12.7, h: 6.2 },
        });
      }

      // Footer
      const timestamp = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
      slide.addText(`Generated by DashSnap — ${timestamp}`, {
        x: 0.4,
        y: 7.1,
        w: 10,
        h: 0.3,
        fontSize: 8,
        fontFace: 'Segoe UI',
        color: footerText,
      });
    }

    // Generate output path
    const outputDir = settings.outputPath ||
      path.join(this.config.getBasePath(), '..', 'output');
    if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

    const now = new Date();
    const ts = now.toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const filename = `DashSnap_${ts}.pptx`;
    const outputPath = path.join(outputDir, filename);

    await pptx.writeFile({ fileName: outputPath });
    return outputPath;
  }
}
